[env]
TERM = "xterm-256color"

[shell]
program = "zsh"
# program = "zellij"

[window]
padding.x = 16
padding.y = 14
decorations = "None"
opacity = 0.7
dynamic_padding = false


[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
